Repository neo4j/sdn-rx, pull requests merged in 2020-02, with the labels that each got.

#135 Make sure all records are retrieved before consuming the result.
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/DefaultReactiveNeo4jClient.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/core/ReactiveNeo4jClientTest.java
Labels: bug

#137 Prevent NPE when non existing properties are mapped onto primitive fields.
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/mapping/DefaultNeo4jConverter.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/TypeConversionIT.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/shared/Neo4jConversionsITBase.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/shared/ThingWithNonExistingPrimitives.java
Labels: bug

#136 Add exception translations.
  spring-data-neo4j-rx-spring-boot-starter-parent/spring-data-neo4j-rx-spring-boot-autoconfigure/src/test/java/org/neo4j/springframework/boot/autoconfigure/data/Neo4jDataAutoConfigurationTest.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/DefaultNeo4jClient.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/DefaultReactiveNeo4jClient.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/schema/UnknownEntityException.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/repository/support/Neo4jPersistenceExceptionTranslator.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/repository/support/ReactiveNeo4jRepositoryFactory.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/repository/support/ReactivePersistenceExceptionTranslationInterceptor.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/repository/support/ReactivePersistenceExceptionTranslationPostProcessor.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/ExceptionTranslationIT.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/reactive/ReactiveExceptionTranslationIT.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/repository/support/Neo4jPersistenceExceptionTranslatorTest.java
Labels: missing-feature

#140 Make Spring Boot autoconfiguration aware of custom EnableNeo4jRepositories.
  examples/reactive-web/src/main/resources/application.properties
  examples/reactive-web/src/test/java/org/neo4j/springframework/data/examples/spring_boot/RepositoryIT.java
  spring-data-neo4j-rx-spring-boot-starter-parent/spring-data-neo4j-rx-spring-boot-autoconfigure/src/main/java/org/neo4j/springframework/boot/autoconfigure/data/Neo4jImperativeRepositoriesConfiguration.java
  spring-data-neo4j-rx-spring-boot-starter-parent/spring-data-neo4j-rx-spring-boot-autoconfigure/src/main/java/org/neo4j/springframework/boot/autoconfigure/data/Neo4jReactiveRepositoriesConfiguration.java
  spring-data-neo4j-rx-spring-boot-starter-parent/spring-data-neo4j-rx-spring-boot-autoconfigure/src/test/java/org/neo4j/springframework/boot/autoconfigure/data/Neo4jRepositoriesAutoConfigurationTest.java
  spring-data-neo4j-rx-spring-boot-starter-parent/spring-data-neo4j-rx-spring-boot-autoconfigure/src/test/java/org/neo4j/springframework/boot/autoconfigure/data/bikes/ReactiveBikeRepository.java
  spring-data-neo4j-rx-spring-boot-starter-parent/spring-data-neo4j-rx-spring-boot-autoconfigure/src/test/java/org/neo4j/springframework/boot/autoconfigure/data/more_bikes/OtherBikeRepository.java
  spring-data-neo4j-rx-spring-boot-starter-parent/spring-data-neo4j-rx-spring-boot-autoconfigure/src/test/java/org/neo4j/springframework/boot/autoconfigure/data/more_bikes/OtherReactiveBikeRepository.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/repository/config/EnableReactiveNeo4jRepositories.java
Labels: bug

#153 Add FAQ entries for parameters in queries and SpEL.
  docs/.gradle/6.2/executionHistory/executionHistory.bin
  docs/.gradle/6.2/executionHistory/executionHistory.lock
  docs/.gradle/6.2/fileChanges/last-build.bin
  docs/.gradle/6.2/fileHashes/fileHashes.bin
  docs/.gradle/6.2/fileHashes/fileHashes.lock
  docs/.gradle/6.2/gc.properties
  docs/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  docs/.gradle/buildOutputCleanup/cache.properties
  docs/.gradle/buildOutputCleanup/outputFiles.bin
  docs/.gradle/checksums/checksums.lock
  docs/.gradle/vcs-1/gc.properties
  docs/faq/faq.adoc
  examples/docs/src/test/java/org/neo4j/doc/springframework/data/docs/repositories/domain_events/ARepository.java
  examples/docs/src/test/java/org/neo4j/doc/springframework/data/docs/repositories/domain_events/DomainEventsTest.java
Labels: documentation

#149 Convert repository method parameters.
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/convert/Neo4jConverter.java
  spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/repository/query/Neo4jQuerySupport.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/PersonRepository.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryIT.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/reactive/ReactivePersonRepository.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/reactive/ReactiveRepositoryIT.java
  spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/repository/query/RepositoryQueryTest.java
Labels: bug
